name: Publish Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: clone
      uses: actions/checkout@v2
      with: 
        repository:  branc116/units-core
        submodules: 1
    - name: SetKeysPriv
      run: \n
        [System.Environment]::SetEnvironmentVariable("Priv", @"\n
        ${{ secrets.SSH_PRIVATE }}"@, [System.EnvironmentVariableTarget]::User)
      shell: powershell
    - name: SetKeysPub
      run: \n
        b = [System.Environment]::SetEnvironmentVariable("Pub", @"\n
        ${{ secrets.SSH_PUBLIC }}"@, [System.EnvironmentVariableTarget]::User)
      shell: powershell
    - name: Setup keys
      run: Scripts/SetKeys.ps1
      shell: powershell
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Build docs
      run: Scripts/PublishDocumentation.ps1
      shell: powershell
